
# I will develop from scratch on actual presentaion
openapi: 3.0.0

info:
  title: "Customer API"
  version: "1.0.0"
  contact:
    name: Accenture
    email: contact@example.com
    url: https://example.com/

tags:
  - name: Customer API
    description: Customer Service related operations
    
paths:
  /customer/{id}:
    get:
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          description: find customer
          required: true
          schema: 
            type: string
          
      summary: Get customer details
      tags: [ 'Customer API' ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error
        '404':
          description: Customer Not Found
        '400':
          description: Invalid ID supplied
          
  /createCustomer:
    post:
      description: Create Customer
      summary: Create Customer
      tags: [ 'Customer API' ]
      operationId: createCustomer
      requestBody:
        description: "Create Customer"
        content:
         application/json:
          schema:
            $ref: '#/components/schemas/Customer'   
      responses:
        '200':
          description: Customer Create Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
           description: Internal Server       

components:
  schemas:
    Customer:
      description: This is a customer model
      type: object
      required:
        - "customerId"
      properties:
        id:
          type: string
          description: Mongo document unique ID
          example: Generated by the application 
        customerId:
          type: string
          description: "Id of the customer"
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          description: Name of the customer
          example: Jessica Alba
        customerAddress:
          type: string
          description: Customer address
          example: 900 Main Street, 55 




        